#!/bin/bash

# Check if the data.json file exists
if [ ! -f data.json ]; then
    echo "Error: data.json not found. Please run the previous script first."
    exit 1
fi

# Extract data from JSON file using jq and format it into a single comma-separated line.
POKEMON_DATA=$(jq -r '"\(.name),\(.types[0].type.name),\(.weight / 10),\(.height / 10)"' data.json)

#Check if extraction with jq was successful
if [ $? -ne 0 ]; then
    echo "Error: Failed to extract data from data.json using jq. Cehck JSON file integrity."
    exit 1
fi

#Use awk to parse comma-separated string and format the final output
FORMATTED_COMPONENTS_AWK=$(echo "$POKEMON_DATA" | awk -F',' '{
    name_formatted = toupper(substr($1, 1, 1)) substr($1, 2)
    type_formatted = toupper(substr($2, 1, 1)) substr($2, 2)
    formatted_weight = sprintf("%.0f", $3)
    formatted_height = sprintf("%.1f", $4)

     print name_formatted, type_formatted, formatted_weight, formatted_height
}')

FINAL_COMPONENTS_FOR_SHELL=$(echo "$FORMATTED_COMPONENTS_AWK" | sed -r 's/(.*)/\1/')

read -r name type formatted_weight formatted_height <<< "$FINAL_COMPONENTS_FOR_SHELL"


echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."

